### ISSUE TITLE
Folder path for C3D

### ISSUE THREAD

**Issue by KristyCh** [mottmacdonaldglobal/Sandbox#35]
Hi, Congrats on launching MM Sandbox!

Whether it was only for me or not, I'm not sure, the path for Dynamo package was slightly different from the Installation instruction. 
Roaming after AppData folder. 

C:\Users\{User}\AppData\Roaming\Autodesk\C3D {VERSION}\Dynamo\{VERSION}\packages

Thank you.

**Comment by TonTon-MM** [comment]
> Hi, Congrats on launching MM Sandbox!
> 
> Whether it was only for me or not, I'm not sure, the path for Dynamo package was slightly different from the Installation instruction. Roaming after AppData folder.
> 
> C:\Users{User}\AppData\Roaming\Autodesk\C3D {VERSION}\Dynamo{VERSION}\packages
> 
> Thank you.

Thanks for reporting Kristy

**Comment by sonomirco** [comment]
Thanks, @KristyCh for the information.
Dynamo is looking into different folders, your directory is one of the other possible locations.
So I'll add it to the installation note.

**Comment by sonomirco** [comment]
After quick research on forums, the general path to the C3D is what is already written in the ReadMe.
So probably @KristyCh you have a special case :)
