### ISSUE TITLE
Analytics for Sandbox

### ISSUE THREAD

**Issue by sonomirco** [mottmacdonaldglobal/Sandbox#58]
I would like to catch some analytics to have a better idea about the use of Sandbox.

**Comment by WilliamHamiltonMM** [comment]
Is this data that would be available to all users or just devs?

**Comment by sonomirco** [comment]
Is more to evaluate the product in its overall, but I am thinking the data could be accessible via a PowerBi or website.

**Comment by sonomirco** [comment]
Move it into the discussions.
