### ISSUE TITLE
Excel reader add toggle

### ISSUE THREAD

**Issue by sonomirco** [mottmacdonaldglobal/Sandbox#80]
Two solutions:
1. Adding a toggle
2. Adding a button and keeping the persistence of the data.

@shuzmm is this what you were suggesting?

**Comment by shuzmm** [comment]
@sonomirco Yes a toggle to start the streaming of data so if in case you had multiple excel files they don't all load at once. And you can stage the loading for better stability

**Comment by sonomirco** [comment]
@shuzmm 
![image](https://user-images.githubusercontent.com/57708659/158580741-b874bc0e-1756-42f0-bfbf-09c8b8b6eaf4.png)

I think this is better :)
