### ISSUE TITLE
Excel reader name ranges

### ISSUE THREAD

**Issue by sonomirco** [mottmacdonaldglobal/Sandbox#81]
@alexandergriffiths526 could you provide more details?

**Comment by alexandergriffiths526** [comment]
Hi @sonomirco,
When we use excel to do calculations we often use the named range function in excel. You can give a cell range in the workbook/worksheet a name. The name is unique in that workbook/worksheet. In a similar way to how your sheetnames component works I thought it might be possible to get a list of all the named ranges in an excel workbook and use a named range from that list to input into the excel reader. 
![image](https://user-images.githubusercontent.com/86045191/158217020-418b6db7-ef7b-47ae-abf0-0445671f71fc.png)

**Comment by WilliamHamiltonMM** [comment]
This looks like a great function to add. @sonomirco do you know if it's possible to access this kind of data from excel package we are using?

**Comment by sonomirco** [comment]
Yes we can!
![image](https://user-images.githubusercontent.com/57708659/158283591-9442252a-f88b-4d5b-a701-6f8d16df3558.png)

**Comment by alexandergriffiths526** [comment]
This looks excellent! And yes It would be really useful if you could also extract the range data as you describe.
