### ISSUE TITLE
Allow different file extensions for excel writer

### ISSUE THREAD

**Issue by alexandergriffiths526** [mottmacdonaldglobal/Sandbox#83]
I often use macro-enabled excel files (.xlsm) would it be possible to include an option to change the file extension on the excel writer?

**Comment by sonomirco** [comment]
What other extensions are you looking for?

**Comment by alexandergriffiths526** [comment]
Personally, I am just looking for .xlsm.

**Comment by sonomirco** [comment]
Cool, it should be a problem.
I gonna start to work on your suggestions tomorrow.

**Comment by sonomirco** [comment]
@alexandergriffiths526 
![image](https://user-images.githubusercontent.com/57708659/158730697-109ee287-8e94-480f-9191-ee54cdd2f359.png)

I'll try to have everything for tomorrow.
